<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 6 </font>
Time2019-08-10 17:43:15
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 6 </font>
Time2019-08-10 17:43:16
*/
?>
<?php  exit();
/*
Page: /index.php
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 6 </font>
Time2019-08-10 22:45:42
*/
?>
<?php  exit();
/*
Page: /index.php
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc limit 0, 6 </font>
Time2019-08-10 22:45:45
*/
?>
